-- Create a read-only (select) user to view database state in running application.
-- DROP USER IF EXISTS guest;
-- CREATE USER guest PASSWORD 'guest';

-- The default schema in H2 is 'PUBLIC'.
GRANT SELECT ON SCHEMA PUBLIC TO guest;


DROP TABLE IF EXISTS BOOK_CATEGORIES CASCADE;
CREATE TABLE BOOK_CATEGORIES
(
    ID          IDENTITY     NOT NULL COMMENT 'A surrogate primary key id, instead of the name.' PRIMARY KEY,
    NAME        VARCHAR(250) NOT NULL COMMENT 'A unique name of the book category' UNIQUE CHECK REGEXP_LIKE(NAME, '^[0-9a-zA-Z -]{2,250}$'),
    PARENT_ID   VARCHAR(20)  NULL COMMENT 'The parent book category',
    DESCRIPTION VARCHAR(255) NULL COMMENT 'A description describing the book category.',
    CREATED_AT  TIMESTAMP(9) WITHOUT TIME ZONE NOT NULL COMMENT 'A timestamp when the book category is created.'
);
COMMENT ON TABLE BOOK_CATEGORIES IS 'Book Category';
CREATE INDEX BOOK_CATEGORIES_NAME_INDEX ON BOOK_CATEGORIES (NAME);
CREATE INDEX BOOK_CATEGORIES_PARENT_ID_INDEX ON BOOK_CATEGORIES (PARENT_ID);
CREATE INDEX BOOK_CATEGORIES_CREATED_AT_INDEX ON BOOK_CATEGORIES (CREATED_AT);


DROP TABLE IF EXISTS BOOK_AUTHORS CASCADE;
DROP TABLE IF EXISTS BOOKS CASCADE;
CREATE TABLE BOOKS
(
    ID               IDENTITY     NOT NULL COMMENT 'A surrogate primary key id, instead of the name.' PRIMARY KEY,
    NAME             VARCHAR(250) NOT NULL COMMENT 'The name of the book',
    CATEGORY_ID      INTEGER      NOT NULL COMMENT 'The category of the book',
    PUBLICATION_DATE DATE         NOT NULL COMMENT 'A publish date of the book.',
    CREATED_AT       TIMESTAMP(9) WITHOUT TIME ZONE NOT NULL COMMENT 'A timestamp when the book is created.'
);
COMMENT ON TABLE books IS 'Book';
CREATE INDEX BOOKS_NAME_INDEX ON BOOKS (NAME);
CREATE INDEX BOOKS_CATEGORY_ID_INDEX ON BOOKS (CATEGORY_ID);
CREATE INDEX BOOKS_PUBLICATION_DATE_INDEX ON BOOKS (PUBLICATION_DATE);
CREATE INDEX BOOKS_CREATED_AT_INDEX ON BOOKS (CREATED_AT);

DROP TABLE IF EXISTS BOOK_AUTHORS CASCADE;
CREATE TABLE BOOK_AUTHORS
(
    ID          IDENTITY     NOT NULL COMMENT 'A surrogate primary key id, instead of the name.' PRIMARY KEY,
    FIRSTNAME   VARCHAR(150)  NOT NULL COMMENT 'The first name of the book author',
    MIDDLE_NAME VARCHAR(150)  NULL COMMENT 'The middle name of the book author',
    LASTNAME    VARCHAR(150)  NOT NULL COMMENT 'The last name of the book author',
    CREATED_AT  TIMESTAMP(9) WITHOUT TIME ZONE NOT NULL COMMENT 'A timestamp when the book author is created.'
);
COMMENT ON TABLE BOOK_AUTHORS IS 'Book author';
CREATE INDEX BOOK_AUTHORS_FIRSTNAME_INDEX ON BOOK_AUTHORS (FIRSTNAME);
CREATE INDEX BOOK_AUTHORS_LASTNAME_INDEX ON BOOK_AUTHORS (LASTNAME);
CREATE INDEX BOOK_AUTHORS_CREATED_AT_INDEX ON BOOK_AUTHORS (CREATED_AT);

CREATE TABLE BOOKS_BOOKS_AUTHORS
(
    BOOK_ID   INTEGER  NOT NULL COMMENT 'The id of the book',
    AUTHOR_ID INTEGER  NOT NULL COMMENT 'The id of the author'
);
CREATE INDEX BOOK_AUTHORS_BOOK_ID_AUTHOR_ID ON BOOKS_BOOKS_AUTHORS (BOOK_ID, AUTHOR_ID);
